# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "demo-piku"
client_id = "7795b3f04687f678197e2621d423b753"
application_url = "https://1a27-2401-4900-4dd1-6d50-9571-64b5-5d84-78b4.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://1a27-2401-4900-4dd1-6d50-9571-64b5-5d84-78b4.ngrok-free.app/auth/callback",
  "https://1a27-2401-4900-4dd1-6d50-9571-64b5-5d84-78b4.ngrok-free.app/auth/shopify/callback",
  "https://1a27-2401-4900-4dd1-6d50-9571-64b5-5d84-78b4.ngrok-free.app/api/auth/callback",
  "https://1a27-2401-4900-4dd1-6d50-9571-64b5-5d84-78b4.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-piku.myshopify.com"
